<a href="https://colab.research.google.com/github/seunghwan1228/Text_Generation/blob/master/Generate_text_with_sklearn_keras_percy_jacson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import keras
from keras.preprocessing.sequence import TimeseriesGenerator
from sklearn.preprocessing import OneHotEncoder
from keras import models, layers
from scipy.sparse import csr_matrix
import sys
import warnings
warnings.filterwarnings('ignore')

Using TensorFlow backend.


In [0]:
text = open('/content/drive/My Drive/Colab Notebooks/Deep_Learning_with_Keras/Generating with keras/percy_jacson.txt').read().lower().strip()

In [0]:
text

'the last olympian \n\n\npercy jackson and the olympians - book 5 \nrick riordan \n\n\none \n\ni go cruising with \nexplosives \n\nthe end of the world started when a pegasus landed on the hood of my car. \n\nup until then, i was having a great afternoon. technically i wasn’t supposed to be driving \nbecause i wouldn’t turn sixteen for another week, but my mom and my stepdad, paul, took my \nfriend rachel and me to this private stretch of beach on the south shore, and paul let us borrow \nhis prius for a short spin. \n\nnow, 1 know you\'re thinking, wow, that was really irresponsible of him, blah, blah, blah, but paul \nknows me pretty well. he\'s seen me slice up demons and leap out of exploding school buildings, so he \nprobably figured taking a car a few hundred yards wasn\'t exactly the most dangerous thing i\'d ever done. \n\nanyway, rachel and i were driving along. it was a hot august day. rachel\'s red hair was pulled back \nin a ponytail and she wore a white blouse over her swi

In [0]:
len(text)

509123

# create character dictionary index

In [0]:
char_index = sorted(set(text))

len(char_index)  # total 59 characters 

59

In [0]:
print(char_index)

['\n', ' ', '!', '"', '$', '&', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '~', '°', '—', '’', '”']


In [0]:
char_to_int = {c:i for i, c in enumerate(char_index)}
int_to_char = {i:c for i, c in enumerate(char_index)}

In [0]:
# check the character and word index

char_to_int

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '$': 4,
 '&': 5,
 "'": 6,
 '(': 7,
 ')': 8,
 '*': 9,
 ',': 10,
 '-': 11,
 '.': 12,
 '/': 13,
 '0': 14,
 '1': 15,
 '2': 16,
 '3': 17,
 '4': 18,
 '5': 19,
 '6': 20,
 '7': 21,
 '8': 22,
 '9': 23,
 ':': 24,
 ';': 25,
 '?': 26,
 'a': 27,
 'b': 28,
 'c': 29,
 'd': 30,
 'e': 31,
 'f': 32,
 'g': 33,
 'h': 34,
 'i': 35,
 'j': 36,
 'k': 37,
 'l': 38,
 'm': 39,
 'n': 40,
 'o': 41,
 'p': 42,
 'q': 43,
 'r': 44,
 's': 45,
 't': 46,
 'u': 47,
 'v': 48,
 'w': 49,
 'x': 50,
 'y': 51,
 'z': 52,
 '|': 53,
 '~': 54,
 '°': 55,
 '—': 56,
 '’': 57,
 '”': 58}

In [0]:
# check the character and word index
int_to_char


{0: '\n',
 1: ' ',
 2: '!',
 3: '"',
 4: '$',
 5: '&',
 6: "'",
 7: '(',
 8: ')',
 9: '*',
 10: ',',
 11: '-',
 12: '.',
 13: '/',
 14: '0',
 15: '1',
 16: '2',
 17: '3',
 18: '4',
 19: '5',
 20: '6',
 21: '7',
 22: '8',
 23: '9',
 24: ':',
 25: ';',
 26: '?',
 27: 'a',
 28: 'b',
 29: 'c',
 30: 'd',
 31: 'e',
 32: 'f',
 33: 'g',
 34: 'h',
 35: 'i',
 36: 'j',
 37: 'k',
 38: 'l',
 39: 'm',
 40: 'n',
 41: 'o',
 42: 'p',
 43: 'q',
 44: 'r',
 45: 's',
 46: 't',
 47: 'u',
 48: 'v',
 49: 'w',
 50: 'x',
 51: 'y',
 52: 'z',
 53: '|',
 54: '~',
 55: '°',
 56: '—',
 57: '’',
 58: '”'}

# to One-Hot encoding the generated data, fit the ohe instant to fit the character index


## !! ) will convert the data to sparse array, required to change dtype as np.unit8  to reduce the memory usage

In [0]:
char_index_numeric = [char_to_int[char] for char in char_index]

In [0]:
char_index_numeric = np.array(char_index_numeric)

In [0]:
ohe = OneHotEncoder(sparse=False, dtype=np.uint8)

ohe.fit(char_index_numeric.reshape(-1,1))


OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.uint8'>, handle_unknown='error',
              n_values=None, sparse=False)

In [0]:
ohe.get_feature_names()

array(['x0_0.0', 'x0_1.0', 'x0_2.0', 'x0_3.0', 'x0_4.0', 'x0_5.0',
       'x0_6.0', 'x0_7.0', 'x0_8.0', 'x0_9.0', 'x0_10.0', 'x0_11.0',
       'x0_12.0', 'x0_13.0', 'x0_14.0', 'x0_15.0', 'x0_16.0', 'x0_17.0',
       'x0_18.0', 'x0_19.0', 'x0_20.0', 'x0_21.0', 'x0_22.0', 'x0_23.0',
       'x0_24.0', 'x0_25.0', 'x0_26.0', 'x0_27.0', 'x0_28.0', 'x0_29.0',
       'x0_30.0', 'x0_31.0', 'x0_32.0', 'x0_33.0', 'x0_34.0', 'x0_35.0',
       'x0_36.0', 'x0_37.0', 'x0_38.0', 'x0_39.0', 'x0_40.0', 'x0_41.0',
       'x0_42.0', 'x0_43.0', 'x0_44.0', 'x0_45.0', 'x0_46.0', 'x0_47.0',
       'x0_48.0', 'x0_49.0', 'x0_50.0', 'x0_51.0', 'x0_52.0', 'x0_53.0',
       'x0_54.0', 'x0_55.0', 'x0_56.0', 'x0_57.0', 'x0_58.0'],
      dtype=object)

# convert the text by character index

In [0]:
convert_text = [char_to_int[char] for char in text]

In [0]:
# convert dtype the converted text to numpy array

convert_array = np.array(convert_text)
print(convert_array.shape)
convert_array


(509123,)


array([46, 34, 31, ..., 29, 37, 12])

# create word sequence data

In [0]:
data_gen = TimeseriesGenerator(convert_array, convert_array, length=500, batch_size=convert_array.shape[0], stride=2)

data_gen

In [0]:
x = []
y= []
for data in data_gen:
#   print(data)
  x.append(data[0])
  y.append(data[1])
  
x = np.array(x[0])
y= np.array(y[0])

print('x Data generated')
print()
print(x)
print('-----------------------')
print('y Data generated')
print()
print(y)


x Data generated

[[46 34 31 ...  1 45 42]
 [31  1 38 ... 42 35 40]
 [38 27 45 ... 40 12  1]
 ...
 [28 31  1 ... 41 37  1]
 [ 1 46 34 ...  1 28 27]
 [34 31  1 ... 27 29 37]]
-----------------------
y Data generated

[35 12  0 ... 28 29 12]


In [0]:
print(x.shape)

print(y.shape)

(254312, 500)
(254312,)


# Model strategy :

1) convert the data and train the model ( x , y )

2) sample the random start sequence

3) predict (2) 

4) concat the predict to (2)

5) predict (4)

...  loop over ...

## 1) 

to feed the data, requires to conver to one hot (because LSTM required 3D tensor : (sample, embedd, length))

However, I choose to convert the data as One-Hot encoding

In [0]:
x[0]

array([46, 34, 31,  1, 38, 27, 45, 46,  1, 41, 38, 51, 39, 42, 35, 27, 40,
        1,  0,  0,  0, 42, 31, 44, 29, 51,  1, 36, 27, 29, 37, 45, 41, 40,
        1, 27, 40, 30,  1, 46, 34, 31,  1, 41, 38, 51, 39, 42, 35, 27, 40,
       45,  1, 11,  1, 28, 41, 41, 37,  1, 19,  1,  0, 44, 35, 29, 37,  1,
       44, 35, 41, 44, 30, 27, 40,  1,  0,  0,  0, 41, 40, 31,  1,  0,  0,
       35,  1, 33, 41,  1, 29, 44, 47, 35, 45, 35, 40, 33,  1, 49, 35, 46,
       34,  1,  0, 31, 50, 42, 38, 41, 45, 35, 48, 31, 45,  1,  0,  0, 46,
       34, 31,  1, 31, 40, 30,  1, 41, 32,  1, 46, 34, 31,  1, 49, 41, 44,
       38, 30,  1, 45, 46, 27, 44, 46, 31, 30,  1, 49, 34, 31, 40,  1, 27,
        1, 42, 31, 33, 27, 45, 47, 45,  1, 38, 27, 40, 30, 31, 30,  1, 41,
       40,  1, 46, 34, 31,  1, 34, 41, 41, 30,  1, 41, 32,  1, 39, 51,  1,
       29, 27, 44, 12,  1,  0,  0, 47, 42,  1, 47, 40, 46, 35, 38,  1, 46,
       34, 31, 40, 10,  1, 35,  1, 49, 27, 45,  1, 34, 27, 48, 35, 40, 33,
        1, 27,  1, 33, 44

In [0]:
x[1]

array([31,  1, 38, 27, 45, 46,  1, 41, 38, 51, 39, 42, 35, 27, 40,  1,  0,
        0,  0, 42, 31, 44, 29, 51,  1, 36, 27, 29, 37, 45, 41, 40,  1, 27,
       40, 30,  1, 46, 34, 31,  1, 41, 38, 51, 39, 42, 35, 27, 40, 45,  1,
       11,  1, 28, 41, 41, 37,  1, 19,  1,  0, 44, 35, 29, 37,  1, 44, 35,
       41, 44, 30, 27, 40,  1,  0,  0,  0, 41, 40, 31,  1,  0,  0, 35,  1,
       33, 41,  1, 29, 44, 47, 35, 45, 35, 40, 33,  1, 49, 35, 46, 34,  1,
        0, 31, 50, 42, 38, 41, 45, 35, 48, 31, 45,  1,  0,  0, 46, 34, 31,
        1, 31, 40, 30,  1, 41, 32,  1, 46, 34, 31,  1, 49, 41, 44, 38, 30,
        1, 45, 46, 27, 44, 46, 31, 30,  1, 49, 34, 31, 40,  1, 27,  1, 42,
       31, 33, 27, 45, 47, 45,  1, 38, 27, 40, 30, 31, 30,  1, 41, 40,  1,
       46, 34, 31,  1, 34, 41, 41, 30,  1, 41, 32,  1, 39, 51,  1, 29, 27,
       44, 12,  1,  0,  0, 47, 42,  1, 47, 40, 46, 35, 38,  1, 46, 34, 31,
       40, 10,  1, 35,  1, 49, 27, 45,  1, 34, 27, 48, 35, 40, 33,  1, 27,
        1, 33, 44, 31, 27

In [0]:
x.reshape(-1,1)

array([[46],
       [34],
       [31],
       ...,
       [27],
       [29],
       [37]])

## Concatnate Strategy

In [0]:
x_ohe_1 = ohe.transform(x[0].reshape(-1,1))


x_ohe_1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [0]:
x_ohe_2 = ohe.transform(x[1].reshape(-1,1))

x_ohe_2

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [0]:
np.concatenate([x_ohe_1, x_ohe_2]).reshape(2,500,59)

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8)

# By follow the above strategy, create  full_x_ohe 

In [0]:
x

array([[46, 34, 31, ...,  1, 45, 42],
       [31,  1, 38, ..., 42, 35, 40],
       [38, 27, 45, ..., 40, 12,  1],
       ...,
       [28, 31,  1, ..., 41, 37,  1],
       [ 1, 46, 34, ...,  1, 28, 27],
       [34, 31,  1, ..., 27, 29, 37]])

In [0]:
full_ohe_list = []
for seq in x:
  ohe_converted = ohe.transform(seq.reshape(-1,1))  # return csr matrix
  full_ohe_list.append(ohe_converted)

In [0]:
full_ohe_list

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), array([[0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0]], dtype=uint8), array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]], dtype=uint8), array([[0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
 

In [0]:
full_ohe = np.concatenate(full_ohe_list)

In [0]:
full_ohe

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [0]:
full_ohe.shape

(127156000, 59)

In [0]:
full_ohe = full_ohe.reshape(-1, 500, 59)

In [0]:
full_ohe.shape

(254312, 500, 59)

-----------------------------------------------------------------------------------------------------
## because of memory usage, cannot convert all at once
-----------------------------------------------------------------------------------------------------

In [0]:
x_ohe

<50902300x59 sparse matrix of type '<class 'numpy.float64'>'
	with 50902300 stored elements in Compressed Sparse Row format>

In [0]:
x_ohe_array = x_ohe.toarray()

In [0]:
x_ohe_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## check prepared data

In [0]:
full_ohe

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0]],

       [[0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 

## Convert the y data to one hot

In [0]:
y_cat = ohe.transform(y.reshape(-1,1))

In [0]:
y_cat.shape

(254312, 59)

In [0]:
y[0]

35

In [0]:
y_cat[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [0]:
np.argmax(y_cat[0])

35

# create model

In [0]:
model = models.Sequential()
model.add(layers.LSTM(128, input_shape=(500, 59)))
model.add(layers.Dense(59, activation='softmax'))
model.summary()
model.compile(loss='categorical_crossentropy', optimizer='adam')

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 128)               96256     
_________________________________________________________________
dense_2 (Dense)              (None, 59)                7611      
Total params: 103,867
Trainable params: 103,867
Non-trainable params: 0
_________________________________________________________________


# Sampling data to predict

In [0]:
x.shape

(254312, 500)

In [0]:
sampling_index = np.random.randint(0, x.shape[0], 1)
sampling_index

array([193697])

# to compare the data, train the model

In [0]:
model.fit(full_ohe, y_cat, batch_size=512, epochs=100)

In [0]:
# to increase diversity
y_pred_sample = model.predict(sampling_data_ohe)
y_pred_sample = np.asarray(y_pred_sample, dtype='float64')

temperature_test = 0.5
log_y_pred = np.log(y_pred_sample) / temperature_test
log_y_pred

exp_y_pred = np.exp(log_y_pred)
exp_y_pred

norm_y_pred = exp_y_pred / np.sum(exp_y_pred)
norm_y_pred

np.sum(norm_y_pred)
proba_y = np.random.multinomial(1, norm_y_pred[0], 1)
proba_y

result_test = np.argmax(proba_y)

In [0]:
result_test

31

In [0]:
def re_weight(y_pred, temperature=0.5):
  y_pred = np.asarray(y_pred, dtype='float64')
  log_y_pred = np.log(y_pred) / temperature
  exp_y_pred = np.exp(log_y_pred)
  norm_y_pred = exp_y_pred / np.sum(exp_y_pred)
  proba_y = np.random.multinomial(1, norm_y_pred[0], 1)
  result_index = np.argmax(proba_y)
  return result_index

In [0]:
for epoch in range(1, 20):
  print('epoch :: ', epoch)
  # fit model
  model.fit(full_ohe, y_cat, batch_size=512, epochs=1)

  
  #get sampling sentence before predict
  sampling_index = np.random.randint(0, x.shape[0], 1)
  sampling_data = x[sampling_index]

  sampling_char = [int_to_char[num] for num in sampling_data.tolist()[0]]
  sampling_syntax = ''.join(sampling_char)
  sys.stdout.write(sampling_syntax)
  print()
  print('----------------------------')
  # to predict the next char, convert to data
  sampling_data_ohe = ohe.transform(sampling_data.reshape(-1,1))
  sampling_data_ohe = sampling_data_ohe.reshape(1, 500,59)
  
  print('Generating Text------')
  print()
  # create range of charaters
  for i in range(1000):
    sampling_data_ohe = ohe.transform(sampling_data.reshape(-1,1))
    sampling_data_ohe = sampling_data_ohe.reshape(1, 500,59)

    # predict 
    y_pred = model.predict(sampling_data_ohe)

    y_result = re_weight(y_pred, temperature=0.5)  # ex) 23

    next_char = int_to_char[y_result]
    sys.stdout.write(next_char)

    concat_syntax = sampling_syntax + next_char

    next_predict_data = np.append(sampling_data, y_result)

    sampling_data = next_predict_data[1:]


