<a href="https://colab.research.google.com/github/seunghwan1228/Text_Generation/blob/master/Text_generation_anatomy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
path = open('/content/drive/My Drive/Colab Notebooks/Deep_Learning_with_Keras/Generating with keras/wonder_land.txt').read().lower()

In [3]:
path

'alice\'s adventures in wonderland\n\nlewis carroll\n\nthe millennium fulcrum edition 3.0\n\n\n\n\nchapter i. down the rabbit-hole\n\nalice was beginning to get very tired of sitting by her sister on the\nbank, and of having nothing to do: once or twice she had peeped into the\nbook her sister was reading, but it had no pictures or conversations in\nit, \'and what is the use of a book,\' thought alice \'without pictures or\nconversations?\'\n\nso she was considering in her own mind (as well as she could, for the\nhot day made her feel very sleepy and stupid), whether the pleasure\nof making a daisy-chain would be worth the trouble of getting up and\npicking the daisies, when suddenly a white rabbit with pink eyes ran\nclose by her.\n\nthere was nothing so very remarkable in that; nor did alice think it so\nvery much out of the way to hear the rabbit say to itself, \'oh dear!\noh dear! i shall be late!\' (when she thought it over afterwards, it\noccurred to her that she ought to have wo

In [4]:
len(path)

144430

In [5]:
from keras.preprocessing.sequence import TimeseriesGenerator

Using TensorFlow backend.


In [0]:
maxlen = 100
whole_batch = len(path)

data_gen = TimeseriesGenerator(path, path, length = maxlen, batch_size=whole_batch)

In [0]:
input_data = []
output_data = []
for data in data_gen:
  input_data.append(data[0])
  output_data.append(data[1])

In [0]:
input_text = input_data[0].tolist()
output_text = output_data[0].tolist()

In [9]:
input_text

["alice's adventures in wonderland\n\nlewis carroll\n\nthe millennium fulcrum edition 3.0\n\n\n\n\nchapter i. d",
 "lice's adventures in wonderland\n\nlewis carroll\n\nthe millennium fulcrum edition 3.0\n\n\n\n\nchapter i. do",
 "ice's adventures in wonderland\n\nlewis carroll\n\nthe millennium fulcrum edition 3.0\n\n\n\n\nchapter i. dow",
 "ce's adventures in wonderland\n\nlewis carroll\n\nthe millennium fulcrum edition 3.0\n\n\n\n\nchapter i. down",
 "e's adventures in wonderland\n\nlewis carroll\n\nthe millennium fulcrum edition 3.0\n\n\n\n\nchapter i. down ",
 "'s adventures in wonderland\n\nlewis carroll\n\nthe millennium fulcrum edition 3.0\n\n\n\n\nchapter i. down t",
 's adventures in wonderland\n\nlewis carroll\n\nthe millennium fulcrum edition 3.0\n\n\n\n\nchapter i. down th',
 ' adventures in wonderland\n\nlewis carroll\n\nthe millennium fulcrum edition 3.0\n\n\n\n\nchapter i. down the',
 'adventures in wonderland\n\nlewis carroll\n\nthe millennium fulcrum edition 3.0\n\n\n\

In [10]:
output_text

['o',
 'w',
 'n',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'r',
 'a',
 'b',
 'b',
 'i',
 't',
 '-',
 'h',
 'o',
 'l',
 'e',
 '\n',
 '\n',
 'a',
 'l',
 'i',
 'c',
 'e',
 ' ',
 'w',
 'a',
 's',
 ' ',
 'b',
 'e',
 'g',
 'i',
 'n',
 'n',
 'i',
 'n',
 'g',
 ' ',
 't',
 'o',
 ' ',
 'g',
 'e',
 't',
 ' ',
 'v',
 'e',
 'r',
 'y',
 ' ',
 't',
 'i',
 'r',
 'e',
 'd',
 ' ',
 'o',
 'f',
 ' ',
 's',
 'i',
 't',
 't',
 'i',
 'n',
 'g',
 ' ',
 'b',
 'y',
 ' ',
 'h',
 'e',
 'r',
 ' ',
 's',
 'i',
 's',
 't',
 'e',
 'r',
 ' ',
 'o',
 'n',
 ' ',
 't',
 'h',
 'e',
 '\n',
 'b',
 'a',
 'n',
 'k',
 ',',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'o',
 'f',
 ' ',
 'h',
 'a',
 'v',
 'i',
 'n',
 'g',
 ' ',
 'n',
 'o',
 't',
 'h',
 'i',
 'n',
 'g',
 ' ',
 't',
 'o',
 ' ',
 'd',
 'o',
 ':',
 ' ',
 'o',
 'n',
 'c',
 'e',
 ' ',
 'o',
 'r',
 ' ',
 't',
 'w',
 'i',
 'c',
 'e',
 ' ',
 's',
 'h',
 'e',
 ' ',
 'h',
 'a',
 'd',
 ' ',
 'p',
 'e',
 'e',
 'p',
 'e',
 'd',
 ' ',
 'i',
 'n',
 't',
 'o',
 ' ',
 't',
 'h',
 'e',
 '\n',
 'b',
 'o',


# change text to numeric index

In [0]:
word_index = sorted(set(path))
word_index

word_to_int = {word:indexes for indexes, word in enumerate(word_index)}
int_to_word = {indexes:word for indexes, word in enumerate(word_index)}

In [12]:
word_to_int

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 "'": 4,
 '(': 5,
 ')': 6,
 '*': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '3': 12,
 ':': 13,
 ';': 14,
 '?': 15,
 '[': 16,
 ']': 17,
 '_': 18,
 'a': 19,
 'b': 20,
 'c': 21,
 'd': 22,
 'e': 23,
 'f': 24,
 'g': 25,
 'h': 26,
 'i': 27,
 'j': 28,
 'k': 29,
 'l': 30,
 'm': 31,
 'n': 32,
 'o': 33,
 'p': 34,
 'q': 35,
 'r': 36,
 's': 37,
 't': 38,
 'u': 39,
 'v': 40,
 'w': 41,
 'x': 42,
 'y': 43,
 'z': 44}

In [13]:
int_to_word

{0: '\n',
 1: ' ',
 2: '!',
 3: '"',
 4: "'",
 5: '(',
 6: ')',
 7: '*',
 8: ',',
 9: '-',
 10: '.',
 11: '0',
 12: '3',
 13: ':',
 14: ';',
 15: '?',
 16: '[',
 17: ']',
 18: '_',
 19: 'a',
 20: 'b',
 21: 'c',
 22: 'd',
 23: 'e',
 24: 'f',
 25: 'g',
 26: 'h',
 27: 'i',
 28: 'j',
 29: 'k',
 30: 'l',
 31: 'm',
 32: 'n',
 33: 'o',
 34: 'p',
 35: 'q',
 36: 'r',
 37: 's',
 38: 't',
 39: 'u',
 40: 'v',
 41: 'w',
 42: 'x',
 43: 'y',
 44: 'z'}

In [14]:
path

'alice\'s adventures in wonderland\n\nlewis carroll\n\nthe millennium fulcrum edition 3.0\n\n\n\n\nchapter i. down the rabbit-hole\n\nalice was beginning to get very tired of sitting by her sister on the\nbank, and of having nothing to do: once or twice she had peeped into the\nbook her sister was reading, but it had no pictures or conversations in\nit, \'and what is the use of a book,\' thought alice \'without pictures or\nconversations?\'\n\nso she was considering in her own mind (as well as she could, for the\nhot day made her feel very sleepy and stupid), whether the pleasure\nof making a daisy-chain would be worth the trouble of getting up and\npicking the daisies, when suddenly a white rabbit with pink eyes ran\nclose by her.\n\nthere was nothing so very remarkable in that; nor did alice think it so\nvery much out of the way to hear the rabbit say to itself, \'oh dear!\noh dear! i shall be late!\' (when she thought it over afterwards, it\noccurred to her that she ought to have wo

In [0]:
text_to_int_full = []
for i in path:
  text_to_index = word_to_int[i]
  text_to_int_full.append(text_to_index)

In [16]:
text_to_int_full

[19,
 30,
 27,
 21,
 23,
 4,
 37,
 1,
 19,
 22,
 40,
 23,
 32,
 38,
 39,
 36,
 23,
 37,
 1,
 27,
 32,
 1,
 41,
 33,
 32,
 22,
 23,
 36,
 30,
 19,
 32,
 22,
 0,
 0,
 30,
 23,
 41,
 27,
 37,
 1,
 21,
 19,
 36,
 36,
 33,
 30,
 30,
 0,
 0,
 38,
 26,
 23,
 1,
 31,
 27,
 30,
 30,
 23,
 32,
 32,
 27,
 39,
 31,
 1,
 24,
 39,
 30,
 21,
 36,
 39,
 31,
 1,
 23,
 22,
 27,
 38,
 27,
 33,
 32,
 1,
 12,
 10,
 11,
 0,
 0,
 0,
 0,
 0,
 21,
 26,
 19,
 34,
 38,
 23,
 36,
 1,
 27,
 10,
 1,
 22,
 33,
 41,
 32,
 1,
 38,
 26,
 23,
 1,
 36,
 19,
 20,
 20,
 27,
 38,
 9,
 26,
 33,
 30,
 23,
 0,
 0,
 19,
 30,
 27,
 21,
 23,
 1,
 41,
 19,
 37,
 1,
 20,
 23,
 25,
 27,
 32,
 32,
 27,
 32,
 25,
 1,
 38,
 33,
 1,
 25,
 23,
 38,
 1,
 40,
 23,
 36,
 43,
 1,
 38,
 27,
 36,
 23,
 22,
 1,
 33,
 24,
 1,
 37,
 27,
 38,
 38,
 27,
 32,
 25,
 1,
 20,
 43,
 1,
 26,
 23,
 36,
 1,
 37,
 27,
 37,
 38,
 23,
 36,
 1,
 33,
 32,
 1,
 38,
 26,
 23,
 0,
 20,
 19,
 32,
 29,
 8,
 1,
 19,
 32,
 22,
 1,
 33,
 24,
 1,
 26,
 19,
 40,
 27,
 32

In [17]:
len(text_to_int_full)

144430

In [0]:
data_gen_second = TimeseriesGenerator(text_to_int_full, text_to_int_full, length=100, batch_size=whole_batch)

In [0]:
x = []
y = []
for i in data_gen_second:
  x.append(i[0])
  y.append(i[1])

In [0]:
x = x[0]
y = y[0]

In [21]:
x

array([[19, 30, 27, ..., 10,  1, 22],
       [30, 27, 21, ...,  1, 22, 33],
       [27, 21, 23, ..., 22, 33, 41],
       ...,
       [30, 30,  1, ..., 26, 23,  1],
       [30,  1, 38, ..., 23,  1, 23],
       [ 1, 38, 26, ...,  1, 23, 32]])

In [22]:
x.shape

(144330, 100)

In [23]:
y

array([33, 41, 32, ..., 23, 32, 22])

In [24]:
x.shape

(144330, 100)

In [25]:
y.shape

(144330,)

In [0]:
from keras.utils import to_categorical

In [27]:
y_cat = to_categorical(y)

y_cat
print(y_cat.shape)

(144330, 45)


In [28]:
x_cat = to_categorical(x)

x_cat

print(x_cat.shape)

(144330, 100, 45)


In [29]:
x_cat[0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
from keras import models, layers

In [31]:
len(set(path))

45

In [32]:
model = models.Sequential()
model.add(layers.LSTM(128, input_shape=(100, 45)))
model.add(layers.Dense(45, activation='softmax'))

model.summary()


model.compile(loss='categorical_crossentropy', optimizer='adam')

W0802 03:37:29.854452 140106823608192 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0802 03:37:29.897716 140106823608192 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0802 03:37:29.906605 140106823608192 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0802 03:37:30.215171 140106823608192 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0802 03:37:30.245751 140106823608192 deprecation_wrappe

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 128)               89088     
_________________________________________________________________
dense_1 (Dense)              (None, 45)                5805      
Total params: 94,893
Trainable params: 94,893
Non-trainable params: 0
_________________________________________________________________


In [33]:
model.fit(x_cat, y_cat, batch_size=128, epochs=1)

W0802 03:37:30.422322 140106823608192 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0802 03:37:31.193345 140106823608192 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/1
144330/144330 [==============================] - 215s 1ms/step - loss: 2.5189


# To generate text, 

1) select predict sentence seed 

2) predict by the sentence seed

3) convert the predicted number to text

4) concat to the sentence seed, and drop the first letter 

5) loop 1 to 5

In [0]:
import numpy as np

In [35]:
# select predict sentence seed
# the total len of input data - maxlen -1 (python excluded)

sentence_seed = np.random.randint(0, len(path)-100)
sentence_seed

43181

In [36]:
# to concat the word the sentence, get the word series before changing categorical value, 

start_index = x[sentence_seed]  # get sentence_seed index from word

start_index_cat = to_categorical(start_index, num_classes=len(set(path)))   # change to categorical, set num_classes = nunique value of the text

print(sentence_seed)                                # check seed number
print(start_index_cat)
print(start_index_cat.shape)

start_index_cat = start_index_cat.reshape(1, 100, 45)   # for LSTM required 3D tensor

print(start_index_cat.shape)

43181
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(100, 45)
(1, 100, 45)


In [37]:
# generate original sentence  as text 
print('seed word index: ', start_index)

sentence_seed = []
for i in start_index:
  original_sentence = int_to_word[i]
  sentence_seed.append(original_sentence)

full_sentence_seed = ''.join(sentence_seed)
print('original_sentence : ','\n', full_sentence_seed)

seed word index:  [ 1 19 32 22  1 41 26 27 30 23  1 37 26 23  1 41 19 37  1 34 23 23 36 27
 32 25  1 19 20 33 39 38  1 19 32 42 27 33 39 37 30 43  1 19 31 33 32 25
  0 38 26 23  1 38 36 23 23 37  8  1 19  1 30 27 38 38 30 23  1 37 26 19
 36 34  1 20 19 36 29  1 28 39 37 38  1 33 40 23 36  1 26 23 36  1 26 23
 19 22  1 31]
original_sentence :  
  and while she was peering about anxiously among
the trees, a little sharp bark just over her head m


In [38]:
# predict the index to model

preds = model.predict(start_index_cat)
preds

array([[4.08002175e-04, 8.21113214e-03, 3.37736361e-04, 3.25807050e-04,
        9.16716235e-04, 8.70035583e-05, 9.93316207e-05, 3.12733784e-04,
        8.16831191e-04, 8.20256537e-04, 4.38335846e-04, 1.14062568e-05,
        6.92384901e-06, 1.77568349e-04, 1.64193887e-04, 1.12628346e-04,
        1.66574191e-05, 1.29759792e-05, 1.39302783e-05, 1.22337602e-01,
        2.35148333e-03, 5.52225858e-04, 2.64915143e-04, 2.05334410e-01,
        1.15158027e-02, 6.57379976e-04, 1.64571833e-02, 9.01325271e-02,
        1.39016905e-04, 4.78465343e-04, 8.49601533e-03, 9.54782474e-04,
        6.41467795e-03, 4.07075822e-01, 4.56221215e-03, 1.98430251e-04,
        1.41173927e-02, 2.40542158e-03, 6.47416012e-03, 6.95200935e-02,
        1.91073271e-03, 2.62355339e-03, 1.50649645e-03, 1.01247597e-02,
        1.04192703e-04]], dtype=float32)

In [39]:
# get argmax to which word is the predicted

pred_label = np.argmax(preds)
pred_label

33

In [40]:
# get 38th word 

int_to_word[pred_label]

'o'

In [41]:
# concat to original sentence
print('the next word is : ', '\n', int_to_word[pred_label])
print()

generated_text = full_sentence_seed + int_to_word[pred_label]
print('concat the word with seed sentence : ', '\n', generated_text)

the next word is :  
 o

concat the word with seed sentence :  
  and while she was peering about anxiously among
the trees, a little sharp bark just over her head mo


In [42]:
# concat to the seed by index
print('start_index : seed index')
print(start_index)
print(start_index.shape)
print()


next_start_index = np.append(start_index, np.array(pred_label))
print('appending the predicted index')
print(next_start_index)           # check the last array 4 is appended
print(next_start_index.shape)
print()


# to feed the model, drop the first number 

feed_start_index = next_start_index[1:]

print('feed_start_index')
print(feed_start_index)
print(feed_start_index.shape)


start_index : seed index
[ 1 19 32 22  1 41 26 27 30 23  1 37 26 23  1 41 19 37  1 34 23 23 36 27
 32 25  1 19 20 33 39 38  1 19 32 42 27 33 39 37 30 43  1 19 31 33 32 25
  0 38 26 23  1 38 36 23 23 37  8  1 19  1 30 27 38 38 30 23  1 37 26 19
 36 34  1 20 19 36 29  1 28 39 37 38  1 33 40 23 36  1 26 23 36  1 26 23
 19 22  1 31]
(100,)

appending the predicted index
[ 1 19 32 22  1 41 26 27 30 23  1 37 26 23  1 41 19 37  1 34 23 23 36 27
 32 25  1 19 20 33 39 38  1 19 32 42 27 33 39 37 30 43  1 19 31 33 32 25
  0 38 26 23  1 38 36 23 23 37  8  1 19  1 30 27 38 38 30 23  1 37 26 19
 36 34  1 20 19 36 29  1 28 39 37 38  1 33 40 23 36  1 26 23 36  1 26 23
 19 22  1 31 33]
(101,)

feed_start_index
[19 32 22  1 41 26 27 30 23  1 37 26 23  1 41 19 37  1 34 23 23 36 27 32
 25  1 19 20 33 39 38  1 19 32 42 27 33 39 37 30 43  1 19 31 33 32 25  0
 38 26 23  1 38 36 23 23 37  8  1 19  1 30 27 38 38 30 23  1 37 26 19 36
 34  1 20 19 36 29  1 28 39 37 38  1 33 40 23 36  1 26 23 36  1 26 23 19
 22  

In [43]:
# convert feed_start_index with to_categorical function, and predict

second_predict = to_categorical(feed_start_index, num_classes=45).reshape(1, 100, 45)

print(second_predict)
print(second_predict.shape)


[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
(1, 100, 45)


In [44]:
second_pred = model.predict(second_predict)

print(second_pred)
print()
print('argmax')
second_pred_label = np.argmax(second_pred)

print(second_pred_label)

[[5.51180821e-03 1.08161762e-01 1.51477335e-03 8.65847920e-04
  1.88342109e-03 2.35886444e-04 4.73643478e-04 6.31030125e-04
  7.19058746e-03 3.39258998e-03 3.25980573e-03 8.95357589e-05
  7.33903362e-05 9.84862563e-04 8.96422716e-04 1.24083180e-03
  6.84302868e-05 5.24016359e-05 8.00577182e-05 1.29299220e-02
  6.69036806e-03 2.56738197e-02 1.32504385e-02 1.16004217e-02
  3.05634830e-02 7.55805103e-03 2.52774591e-03 1.12937661e-02
  9.79174045e-04 1.93079561e-02 1.84105542e-02 4.57083434e-02
  6.57929406e-02 5.14411740e-02 1.29475705e-02 9.54048242e-04
  1.99230224e-01 3.91694456e-02 5.99098019e-02 1.38628736e-01
  1.97207667e-02 5.30137718e-02 4.44687763e-03 1.07360855e-02
  9.07327281e-04]]

argmax
36


In [45]:
# get 38th word 

int_to_word[second_pred_label]

'r'

In [46]:
# concat to original sentence
print('the next word is : ', '\n', int_to_word[second_pred_label])
print()
generated_text = full_sentence_seed + int_to_word[pred_label]

generated_text += int_to_word[second_pred_label]
print('concat the word with seed sentence : ', '\n', generated_text)

the next word is :  
 r

concat the word with seed sentence :  
  and while she was peering about anxiously among
the trees, a little sharp bark just over her head mor


### loop the sentence over time


## additinal requirment, after the predict, change the softmax weight  which generate more create sentence

In [47]:
print(second_pred)
print()
print('argmax')
second_pred_label = np.argmax(second_pred)

print(second_pred_label)


print(int_to_word[second_pred_label])



[[5.51180821e-03 1.08161762e-01 1.51477335e-03 8.65847920e-04
  1.88342109e-03 2.35886444e-04 4.73643478e-04 6.31030125e-04
  7.19058746e-03 3.39258998e-03 3.25980573e-03 8.95357589e-05
  7.33903362e-05 9.84862563e-04 8.96422716e-04 1.24083180e-03
  6.84302868e-05 5.24016359e-05 8.00577182e-05 1.29299220e-02
  6.69036806e-03 2.56738197e-02 1.32504385e-02 1.16004217e-02
  3.05634830e-02 7.55805103e-03 2.52774591e-03 1.12937661e-02
  9.79174045e-04 1.93079561e-02 1.84105542e-02 4.57083434e-02
  6.57929406e-02 5.14411740e-02 1.29475705e-02 9.54048242e-04
  1.99230224e-01 3.91694456e-02 5.99098019e-02 1.38628736e-01
  1.97207667e-02 5.30137718e-02 4.44687763e-03 1.07360855e-02
  9.07327281e-04]]

argmax
36
r


In [60]:
## re-weight softmax, to create variety sentence

second_pred

temperature = 0.6
log_pred = np.log(second_pred) / temperature
log_pred

exp_pred = np.exp(log_pred)
exp_pred

scale_exp_pred = exp_pred / np.sum(exp_pred)
scale_exp_pred

np.sum(scale_exp_pred)


pred_proba = np.random.multinomial(1, scale_exp_pred[0], 1)
pred_proba

proba_argmax = np.argmax(pred_proba)
proba_argmax


print(int_to_word[proba_argmax])

v


In [0]:
# wrap as function

def re_weight_sample(pred, temperature=0.6):
  pred = pred.astype('float64')
  log_pred = np.log(pred) / temperature
  exp_pred = np.exp(log_pred)
  scale_exp_pred = exp_pred / np.sum(exp_pred)
  pred_proba = np.random.multinomial(1, scale_exp_pred[0], 1)
  proba_argmax = np.argmax(pred_proba)
  return proba_argmax, int_to_word[proba_argmax]

In [82]:
re_weight_sample(second_pred, 0.5)

(36, 'r')

## create loop

- purpose : create a 4000 character by epochs 

1) train model by 1 epoch

2) sample the seed sentence

3) create a sentence for 4000


In [0]:
import sys

In [97]:
model = models.Sequential()
model.add(layers.LSTM(128, input_shape=(100, 45)))
model.add(layers.Dense(45, activation='softmax'))
# model.summary()
model.compile(loss='categorical_crossentropy', optimizer='adam')



for epoch in range(1, 21):  # set epoch
  model.fit(x_cat, y_cat, batch_size=128, epochs=1)
  sentence_seed = np.random.randint(0, len(path)-100)
  
  start_index = x[sentence_seed]
  
  start_index_cat = to_categorical(start_index, num_classes=len(set(path)))
  start_index_cat = start_index_cat.reshape(1, 100, 45)
  
  sentence_seed_text = []
  for i in start_index:

    original_sentence = int_to_word[i]
    sentence_seed_text.append(original_sentence)
    full_sentence_seed = ''.join(sentence_seed_text)
  print('---------------')
  print()
  print('original_sentence : ','\n', ''.join(sentence_seed_text))
  print()
  print('---------------')
  print()
  
  for i in range(1, 1000):                    # generate 4000 character   ex) original sentence + char_1 + char_2 + char_3 ... char_4000 
    start_index_cat = to_categorical(start_index, num_classes=45).reshape(1, 100, 45)
    preds = model.predict(start_index_cat)
    weighted_softmax, weighted_character = re_weight_sample(preds, temperature=0.6)
    
    next_char = int_to_word[weighted_softmax]
    
    sentence_seed_text.append(next_char)
    
    
    start_index = np.append(start_index, np.array(weighted_softmax))
    start_index = start_index[1:]
    
    sys.stdout.write(weighted_character)
#     print('----------------')
  print()
  print('---------------')
  print()
  print(''.join(sentence_seed_text))
  print()
  print('---------------')
  print()
    

Epoch 1/1
144330/144330 [==============================] - 221s 2ms/step - loss: 2.5348
---------------

original_sentence :  
 ery slowly, for she had
plenty of time as she went down to look about her and to wonder what was
goi

---------------

t she mais se the alith, sas ase saine ther ai she poter the saikat won wand th aiging and inf han the the and sa the thand the soulling in the larlice to theres, sulith gofouthe the bereribe las the foupline the hanes hath aide here moullle said the so he at, fo aly ala got sall of in who tore has an, and the areyfang heren the sarime the wable, you thandy ind i quele the moule shat fores aren the gale, 'the the wor haitime the forsein the wisk he the morsorer af the with the lithe the thith bele arind it ore sure, and quito to bering mouth the aile whand the fur, the atte then' os the the wher sait of aite has woo laveren, she anke was so ave and the deate fore out, a sae caid ther. said sait on merto it she foreer, aw wal ,  i sap' re mat a

In [100]:
for epoch in range(1, 50):  # set epoch
  model.fit(x_cat, y_cat, batch_size=128, epochs=1)
  sentence_seed = np.random.randint(0, len(path)-100)
  
  start_index = x[sentence_seed]
  
  start_index_cat = to_categorical(start_index, num_classes=len(set(path)))
  start_index_cat = start_index_cat.reshape(1, 100, 45)
  
  sentence_seed_text = []
  for i in start_index:

    original_sentence = int_to_word[i]
    sentence_seed_text.append(original_sentence)
    full_sentence_seed = ''.join(sentence_seed_text)
  print('---------------')
  print('epoch : ', epoch)
  print()
  print('original_sentence : ')
  print()
  print(''.join(sentence_seed_text))
  print()
  print('---------------')
  print()
  
  for i in range(1, 1500):                    # generate 4000 character   ex) original sentence + char_1 + char_2 + char_3 ... char_4000 
    start_index_cat = to_categorical(start_index, num_classes=45).reshape(1, 100, 45)
    preds = model.predict(start_index_cat)
    weighted_softmax, weighted_character = re_weight_sample(preds, temperature=0.5)
    
    next_char = int_to_word[weighted_softmax]
    
    sentence_seed_text.append(next_char)
    
    
    start_index = np.append(start_index, np.array(weighted_softmax))
    start_index = start_index[1:]
    
    sys.stdout.write(weighted_character)
#     print('----------------')
  print()
  print('---------------')
  print()
  print(''.join(sentence_seed_text))
  print()
  print('---------------')
  print()

Epoch 1/1
144330/144330 [==============================] - 217s 2ms/step - loss: 1.2232
---------------
epoch :  1

original_sentence : 

stily replied; 'at least--at least i mean what i
say--that's the same thing, you know.'

'not the sa

---------------

me thing is all the white rabbit tried to find her head ready to see alice on her same to the tconsed, and the white rabbit in the court. 'it's hardly door and all the same was a long was a little upon a too consised to see a the was now in a long
arm a great down and hear nother shoulded the rabbit heard the begges that began in a long a let time she had not any mar of the ratmer and dear something any use, and wondering alice felt began and the tret glass in the senter, and the gryphon and at the does.

'they began with a to be no sort of the mouse to the think of
them at once, bet any martance, the mouse duenced to alice to the larger one the white remalked, 'very like the dormouse began some of the white rabbit and some the court

In [0]:
model.save('first_language_model.h5')

In [0]:
!cp /content/first_language_model.h5 /content/drive/'My Drive'/'Colab Notebooks'/Deep_Learning_with_Keras/'Generating with keras'/first_language_model.h5